name: Deploy with remote SSH

on:
    push:
        branches: [ "staging" ]

jobs:
    staging:
        name: Deploy to Staging
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: SSH Connection With Remote Commands
              run: |
                  mkdir -p ~/.ssh/
                  echo -e "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
                  chmod 600 ~/.ssh/id_rsa
                  ssh-keyscan -p 2219 egorovagency.com >> ~/.ssh/known_hosts
                  cat ./deploy-staging.sh | ssh -p 2219 -T e2qr@egorovagency.com
